export const navLink = [
  { name: "Home", href: "/" },
  { name: "About", href: "/about" },
  { name: "Gallery", href: "/gallery" },
  { name: "Contact Us", href: "/contact" },
];

export const clergyFromCurtorim = [
  {
    key: "1",
    name: "Fr. Geraldo Aleixo Antonio Da Costa",
    location: "-",
    dob: "03-10-1939",
    ordained: "10-5-1964",
    ward: "Sinaibhag Curtorim",
  },
  {
    key: "2",
    name: "Fr. Jose Antonio Da Costa",
    location: "Church of Our Lady of Immaculate Conception, Paroda",
    dob: "06-06-1949",
    ordained: "28-4-1973",
    ward: "Sinaibhag Curtorim",
  },
  {
    key: "3",
    name: "Fr. Roque Aleixo Manuel Da Costa",
    location: "Chaplain St. Sebastaian,Fontainhas, Panjim, Goa",
    dob: "22-06-1953",
    ordained: "27-10-1984",
    ward: "Gottunguem Curtorim",
  },
  {
    key: "4",
    name: "Fr. Felicio Piedade dos Milagres Diniz",
    location: "-",
    dob: "16-03-1946",
    ordained: "31-05-1984",
    ward: "Anvottem Curtorim",
  },
  {
    key: "5",
    name: "Fr. Frederico Rodrigues (SFX)",
    location:
      "1. Local Superior, Fr. Agnel Local House Pilar, Goa 2.Off. Principal, Fr. Agnel College of Arts & Commerce, Pilar Goa.",
    dob: "18-01-1964",
    ordained: "19-12-1990",
    ward: "Anvottem Curtorim",
  },
  {
    key: "6",
    name: "Fr. Edwin Epiphanio Baracho(SDB)",
    location: "Rector - Don Bosco Ganv (SDB) Quepem Goa",
    dob: "06-01-1960",
    ordained: "21-04-1990",
    ward: "Kirdolem Curtorim",
  },
  {
    key: "7",
    name: "Fr. Diogo Indira Fernandes (SFX)",
    location:
      "Present work : Archdiocese of Bombay. Mission Station : Nagothane Maharastra",
    dob: "23-09-1967",
    ordained: "30-04-1997",
    ward: "Sonvonxem Curtorim",
  },
  {
    key: "8",
    name: "Fr. Remy Cardozo (SFX)",
    location: "Position Held : Provincial Superior. Present Location : Delhi",
    dob: "06-01-1974",
    ordained: "16-10-2003",
    ward: "Corjem Curtorim",
  },
  {
    key: "9",
    name: "Fr. Manuel Martins (SFX)",
    location: "Vailankanni (TN State)",
    dob: "4th April",
    ordained: "17-05-2014",
    ward: "Agxem Curtorim",
  },
];

export const nuns = [
  {
    key: "1",
    name: "Sr. Joana Dias",
    cong: "Canossian Daughters of Charity",
    pos: "Position Held : Teacher St. Anthony’s School, Galgibaga. Incharge of Vocation Promotion of Goa Region",
    location: "Canossa Convent Galgibaga, Canacona,Goa",
    dob: "10-03-1964",
    profession: "14-09-1987",
    ward: "New Monzon Curtorim",
  },
  {
    key: "2",
    name: "Sr. Flory Ritinha Menezes",
    cong: "Sisters of the Cross of Chavanod (SCC)",
    pos: "Provincial Councilor",
    location:
      "Asara, Sisters of the Cross, Ganesh Krupa Society, Sainikwadi, Vadgaosheri, Pune",
    dob: "19-05-1973",
    profession: "03-05-1994",
    ward: "Corjem Curtorim",
  },
  {
    key: "3",
    name: "Sr. Gracy Rodrigues",
    cong: "Canossian Daughters of Charity Servants of the Poor",
    pos: "Superior and Advocate",
    location:
      "Canossian Sisiters, Stella Maris Convent, Madholo Vaddo, Arambol Goa",
    dob: "04-09-1978",
    profession: "01-10-2002",
    ward: "Gotnibhat Curtorim",
  },
  {
    key: "4",
    name: "Sr. Antoneta Cardozo",
    cong: "Canossian Daughters of Charity",
    pos: "Vice - Principal",
    location: "St. Joseph’s Convent Camp, Belagavi",
    dob: "08-10-1970",
    profession: "19-03-1994",
    ward: "Gotnibhat Curtorim",
  },
  {
    key: "5",
    name: "Sr. Maria Sarita Vaz (Known as Sarita)",
    cong: "Sisters of the Cross of Chavanod",
    pos: "Working as Matron",
    location: "Cipla :Palliative Care Centre, Pune (Maharastra)",
    dob: "08-10-1970",
    profession: "19-03-1994",
    ward: "Tembi Curtorim",
  },
  {
    key: "6",
    name: "Sr. Terezinha Ferrao",
    cong: "Canossian Daughters of Charity",
    pos: "Principal of Canossa, Mahim  Mumbai(A School for the Intellectually Challenged)",
    location: "Mahim, Mumbai",
    dob: "10-08-1967",
    profession: "14-09-1989",
    ward: "Gottunguem Curtorim",
  },
  {
    key: "7",
    name: "Sr. Taurina Vaz",
    cong: "Franciscan Missionaries of Mary",
    pos: "-",
    location: "Kolkata (WB State)",
    dob: "11-08-1944",
    profession: "15-11-1975",
    ward: "St. Anthony Curtorim",
  },
  {
    key: "8",
    name: "Sr. Esperanca Vaz",
    cong: "Canossian Daughters of Charity",
    pos: "Directress of Novices",
    location: "Andheri, Mumbai",
    dob: "30-10-1978",
    profession: "14-09-1999",
    ward: "Sonvonxem Curtorim",
  },
];
